spring.application.name=webshop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6invsa4d50c7385jo2g-a.oregon-postgres.render.com/veebipood_database_w922
spring.datasource.username=veebipood_user
spring.datasource.password=eewlh1QHBgRQkTjFDa4Kj644gN5lKcow

# veebipood_user
# eewlh1QHBgRQkTjFDa4Kj644gN5lKcow
# postgresql://veebipood_user:eewlh1QHBgRQkTjFDa4Kj644gN5lKcow@dpg-d6invsa4d50c7385jo2g-a.oregon-postgres.render.com/veebipood_database_w922












logging.file.name=logs.log

everypay.base-url=https://igw-demo.every-pay.com/api/v4
everypay.username=e36eb40f5ec87fa2
everypay.password=7b91a3b9e1b74524c2e9fc282f8ac8cd
everypay.customer-url=https://err.ee
everypay.order-prefix=tyuijfgh

frontend.url=http://localhost:5173
cron.5min.urls=https://backend-12-2025.onrender.com/products,https://backend-12-2025-webshop-frontend.onrender.com

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=587
#spring.mail.username=f8c1f0cf5e22a2
#spring.mail.password=0b30df2a58aaef
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

cron.expression=0 0 12 * * ?